name: ci
on: [push]
jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: cp package.json dist/
      - run: cd dist/ && npm pack
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      - run: cd dist/ && npm publish --provenance --access public
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
